'use strict';
(()=>{
const figures=Array.from(document.querySelectorAll('.journey-clip'));if(!figures.length)return;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');const ratios=new Map();let active=null,scheduled=false;
const states=new Map(figures.map(f=>[f,{paused:false,manual:false,pending:false,blocked:false}]));
const motionOff=()=>document.body.classList.contains('no-motion')||reduced.matches;
function ui(f){const v=f.querySelector('video'),button=f.querySelector('.clip-toggle');const playing=!v.paused;button.textContent=playing?'Ⅱ':'▶';button.setAttribute('aria-label',playing?'영상 일시정지':'영상 재생');button.setAttribute('aria-pressed',String(playing));f.classList.toggle('playing',playing)}
function stop(f){f.querySelector('video').pause();states.get(f).pending=false;ui(f)}
function start(f){const s=states.get(f),v=f.querySelector('video');if(s.paused||s.blocked||s.pending)return;if(motionOff()&&!s.manual)return;if(!v.src){v.src=v.dataset.src;v.muted=true;v.defaultMuted=true;v.playsInline=true}if(!v.paused)return;s.pending=true;const promise=v.play();if(promise)promise.then(()=>{s.pending=false;if(active!==f||document.hidden||document.querySelector('#lightbox')?.open){stop(f);return}f.querySelector('.clip-loading').textContent='';ui(f)}).catch(e=>{s.pending=false;if(e.name==='AbortError')return;s.blocked=true;f.querySelector('.clip-loading').textContent='자동 재생이 제한되어 재생 버튼을 눌러 주세요.';ui(f)})}
function refresh(){scheduled=false;const modal=document.querySelector('#lightbox')?.open;if(document.hidden||modal){figures.forEach(stop);return}let candidate=null,best=.22;for(const f of figures){const ratio=ratios.get(f)||0;if(ratio>best){best=ratio;candidate=f}}active=candidate;for(const f of figures){if(f!==candidate)stop(f);else{const s=states.get(f);if(motionOff()&&!s.manual)stop(f);else start(f)}}}
function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(refresh)}}
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>ratios.set(e.target.closest('.journey-clip'),e.intersectionRatio));schedule()},{threshold:[0,.1,.22,.3,.4,.5,.6,.7,.8,.9,1]});
for(const f of figures){const v=f.querySelector('video'),s=states.get(f);v.muted=true;v.playsInline=true;observer.observe(f.querySelector('.journey-screen'));f.querySelector('.clip-toggle').onclick=()=>{s.blocked=false;if(!v.paused){s.paused=true;s.manual=false;stop(f)}else{s.paused=false;s.manual=true;active=f;figures.filter(x=>x!==f).forEach(stop);start(f)}};v.addEventListener('playing',()=>{if(active!==f||document.hidden||document.querySelector('#lightbox')?.open){stop(f);return}f.querySelector('.clip-loading').textContent='';ui(f)});v.addEventListener('pause',()=>ui(f));v.addEventListener('waiting',()=>{if(active===f&&!s.paused)f.querySelector('.clip-loading').textContent='장면을 불러오는 중…'});v.addEventListener('error',()=>{s.blocked=true;s.pending=false;f.querySelector('.clip-loading').textContent='영상을 불러오지 못했습니다. 다시 재생해 주세요.';ui(f)})}
document.addEventListener('visibilitychange',refresh);new MutationObserver(()=>{if(motionOff())for(const s of states.values())s.manual=false;refresh()}).observe(document.body,{attributes:true,attributeFilter:['class']});new MutationObserver(refresh).observe(document.querySelector('#lightbox'),{attributes:true,attributeFilter:['open']});reduced.addEventListener('change',refresh);
document.documentElement.dataset.journeyVideos='ready';
})();
