'use strict';
(()=>{
const section=document.querySelector('#scrollFilms');if(!section)return;
const stage=document.querySelector('#filmStage'),video=document.querySelector('#stageVideo'),poster=document.querySelector('#stagePoster'),caption=document.querySelector('#stageCaption'),counter=document.querySelector('#stageCounter'),day=document.querySelector('#stageDay'),status=document.querySelector('#stageStatus'),pause=document.querySelector('#stagePause'),dots=document.querySelector('#stageDots');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let clips=[],index=-1,userPaused=false,manual=false,visible=false,pending=false,blocked=false,raf=false,scrollTimer=null;
const clean=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function motionOff(){return document.body.classList.contains('no-motion')||reduced.matches}
function bounds(){const top=scrollY+section.getBoundingClientRect().top-84;return {top,range:Math.max(1,section.offsetHeight-stage.offsetHeight)}}
function controls(){const stopped=userPaused||(motionOff()&&!manual)||blocked;pause.textContent=stopped?'▶':'Ⅱ';pause.setAttribute('aria-label',stopped?'영상 재생':'영상 일시정지')}
function select(i){if(i===index)return;index=i;const r=clips[i];video.pause();pending=false;blocked=false;poster.src=r.thumb;poster.alt=r.caption;poster.classList.remove('loaded');video.poster=r.thumb;video.src=r.src;video.muted=true;video.defaultMuted=true;video.playsInline=true;video.loop=true;video.setAttribute('aria-label',r.caption);caption.textContent=r.caption;day.textContent=['3','4','5'].includes(r.day)?`OCTOBER 0${r.day}, 2026`:'ON THE ROAD';counter.textContent=`${String(i+1).padStart(2,'0')} / ${clips.length}`;dots.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(j===i)));document.querySelectorAll('#filmRail .film-card').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stageVideo===r.id)));status.textContent=motionOff()&&!manual?'모션 OFF · 재생 버튼으로 보실 수 있습니다.':'';controls()}
function syncPlayback(){if(!clips.length)return;const modal=document.querySelector('#lightbox');const allowed=visible&&!document.hidden&&!modal?.open&&!userPaused&&(!motionOff()||manual);if(!allowed){video.pause();pending=false;controls();return}if(video.paused&&!pending&&!blocked){pending=true;const selected=index;const promise=video.play();if(promise)promise.then(()=>{if(index===selected){pending=false;status.textContent=''}}).catch(e=>{if(index!==selected)return;pending=false;if(e.name==='AbortError')return;blocked=true;status.textContent='자동 재생이 제한되어 재생 버튼을 눌러 주세요.';controls()})}controls()}
function update(){raf=false;if(!clips.length)return;const rect=section.getBoundingClientRect();visible=rect.top<innerHeight*.55&&rect.bottom>innerHeight*.45;if(!motionOff()&&visible){const b=bounds();const ratio=Math.max(0,Math.min(1,(scrollY-b.top)/b.range));const target=Math.min(clips.length-1,Math.floor(ratio*clips.length));if(target!==index){clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{if(visible){select(target);syncPlayback()}},100)}}syncPlayback()}
function schedule(){if(!raf){raf=true;requestAnimationFrame(update)}}
function jump(i){i=Math.max(0,Math.min(clips.length-1,i));clearTimeout(scrollTimer);select(i);if(motionOff()){stage.scrollIntoView({block:'center',behavior:'instant'});manual=true}else{const b=bounds();scrollTo({top:b.top+b.range*((i+.25)/clips.length),behavior:'instant'})}visible=true;syncPlayback()}
pause.onclick=()=>{if(userPaused||motionOff()&&!manual||blocked){userPaused=false;manual=true;blocked=false}else{userPaused=true;manual=false}syncPlayback();controls()};document.querySelector('#stagePrev').onclick=()=>jump(index-1);document.querySelector('#stageNext').onclick=()=>jump(index+1);
video.addEventListener('playing',()=>{poster.classList.add('loaded');status.textContent='';controls()});video.addEventListener('error',()=>{blocked=true;poster.classList.remove('loaded');status.textContent='영상을 불러오지 못했습니다. 다른 장면을 선택해 주세요.';controls()});
video.addEventListener('waiting',()=>{if(visible&&!userPaused)status.textContent='장면을 불러오는 중…'});
addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.addEventListener('visibilitychange',syncPlayback);reduced.addEventListener('change',()=>{manual=false;schedule()});
new MutationObserver(()=>{manual=false;clearTimeout(scrollTimer);schedule()}).observe(document.body,{attributes:true,attributeFilter:['class']});new MutationObserver(syncPlayback).observe(document.querySelector('#lightbox'),{attributes:true,attributeFilter:['open']});
function initClips(e){if(clips.length)return;clips=e.detail.filter(r=>r.type==='video').sort((a,b)=>(Number(a.day)||9)-(Number(b.day)||9));dots.innerHTML=clips.map((r,i)=>`<button data-slide="${i}" aria-label="${i+1}번째 영상: ${clean(r.caption)}" aria-pressed="false"></button>`).join('');dots.onclick=e=>{const b=e.target.closest('[data-slide]');if(b)jump(Number(b.dataset.slide))};const rail=document.querySelector('#filmRail');rail.innerHTML=clips.map(r=>`<button class="film-card" data-stage-video="${r.id}" aria-label="${clean(r.caption)} 장면으로 이동" aria-pressed="false"><div class="film-poster"><img src="${r.thumb}" alt="${clean(r.caption)}" width="700" height="450" loading="lazy"><span class="play" aria-hidden="true">▶</span><span class="duration">${Math.floor(r.duration/60)}:${String(r.duration%60).padStart(2,'0')}</span></div><h3>${clean(r.caption)}</h3></button>`).join('');rail.onclick=e=>{const b=e.target.closest('[data-stage-video]');if(b)jump(clips.findIndex(r=>r.id===b.dataset.stageVideo))};select(0);section.dataset.ready='true';schedule()}
addEventListener('ryu-media-ready',initClips);if(window.ryuMedia)initClips({detail:window.ryuMedia});
})();
